### ISSUE TITLE
دانشگاه تبریز

### ISSUE THREAD

**Issue by aliafshany** [sina-rostami/Adobe-Connect-Based-Meetings#14]
سلام
برای دانشگاه تبریزم اگه بتونید این برنامه رو مدیفای کنید

یا حداقل روشی رو ذکر کنید که بشه فایل های شیر شده جلسات رو بشه دانلود کرد
مثل
pdf

ممنون

**Comment by sina-rostami** [comment]
سلام دوست عزیز حتما
لطفا آدرس سایت دانشگاهتون رو بفرستید برام.

**Comment by aliafshany** [comment]
https://lms1.tabrizu.ac.ir/
ممکن هست که آدرس 
LMS
ها فرق بکنه و عدد ها عوض شه

آدرسی که خود کلاس ها ازش برگزار میشه این هست
https://vc1.tabrizu.ac.ir/
فک کنم روی این باید کار صورت بگیره

**Comment by tahertahmasbi** [comment]
سلام و وقت بخیر
اگه بتونید برای دانشگاه خاتم هم فایل پایتونش رو ادیت کنین ممنون میشم.
آدرس ویدئوها به این صورت هستش  که برای جلسات مختلف عدد آخرش عوض میشه

http://lms.khatam.ac.ir/mod/url/view.php?id=20187

پیشاپیش ممنونم

**Comment by EVOL-ution** [comment]
سلام
دانشگاه صنعتی اصفهان دو تا سامانه اموزشی داره
ادرس سامانه اول
yekta.iut.ac.ir
هست
مشکل اینجاست که برای لاگین به سایت
webauth.iut.ac.ir
ریدایرکت میشیم
اگر ممکنه سورس رو ادیت کن که بشه از سامانه استفاده کرد
یا اگه نمیشه این قابلیت  که با استفاده از کوکی ای که میشه از مرورگر دراورد لاگین کرد رو اضافه کن
![Snag_117bff7](https://user-images.githubusercontent.com/81646149/129480022-f8f1e9b8-064e-4255-8116-4409a9fb5ab3.png)
برای سایت دوم به ادرس
elearning.iut.ac.ir
اسکریپ رو ویرایش کردم
[iut_vc_dl.txt](https://github.com/sina-rostami/Adobe-Connect-Meetings-Downloader/files/6988157/iut_vc_dl.txt)
میتونی به ریپازیتوری  اضافه کنی
ممنون

**Comment by aliafshany** [comment]
سلام من با روشی که گفته بودید فایل زیپ رو دانلود کردم
ولی مشکلی که وجود داره این هست که موقع خروجی گرفتن فایل صوتی وتصویری جداس, تایم هاشون هم یکی نیست تا merge کنم

راهی سراغ دارید تا خروجی تک فایل داشته باشیم؟
ممنون

**Comment by sina-rostami** [comment]
> سلام من با روشی که گفته بودید فایل زیپ رو دانلود کردم
> ولی مشکلی که وجود داره این هست که موقع خروجی گرفتن فایل صوتی وتصویری جداس, تایم هاشون هم یکی نیست تا merge کنم
> 
> راهی سراغ دارید تا خروجی تک فایل داشته باشیم؟
> ممنون

سلام بله خروجی صوت ها رو به هم متصل میکنه این پروژه ولی چون مرج کردنش با تصویر خیلی طول میکشه از نظر زمانی نسبت به رکورد اسکرین فعلا غیر فعاله و دنبال راه سریعش هستیم.

**Comment by aliafshany** [comment]
امکان استفاده از ffmpeg نیست؟
میشه این کار رو انجام داد فقط مشکل این هست که به جای زمان هایی که فایل تصویری شیر نشده, از یک عکس استفاده بشه 
ممنون

**Comment by sina-rostami** [comment]
> امکان استفاده از ffmpeg نیست؟
> میشه این کار رو انجام داد فقط مشکل این هست که به جای زمان هایی که فایل تصویری شیر نشده, از یک عکس استفاده بشه
> ممنون

چرا میشه کدشم الان هست تو ریپوزیتوری ولی کامنته چون برای یک کلاس ۱ ساعتی چیزی حدود ۲ ساعت تبدیلش طول میکشه

**Comment by sina-rostami** [comment]
> سلام
> دانشگاه صنعتی اصفهان دو تا سامانه اموزشی داره
> ادرس سامانه اول
> yekta.iut.ac.ir
> هست
> مشکل اینجاست که برای لاگین به سایت
> webauth.iut.ac.ir
> ریدایرکت میشیم
> اگر ممکنه سورس رو ادیت کن که بشه از سامانه استفاده کرد
> یا اگه نمیشه این قابلیت که با استفاده از کوکی ای که میشه از مرورگر دراورد لاگین کرد رو اضافه کن
> ![Snag_117bff7](https://user-images.githubusercontent.com/81646149/129480022-f8f1e9b8-064e-4255-8116-4409a9fb5ab3.png)
> برای سایت دوم به ادرس
> elearning.iut.ac.ir
> اسکریپ رو ویرایش کردم
> [iut_vc_dl.txt](https://github.com/sina-rostami/Adobe-Connect-Meetings-Downloader/files/6988157/iut_vc_dl.txt)
> میتونی به ریپازیتوری اضافه کنی
> ممنون

سلام این اسکریپت که نوشتی رو تست کردی اوکی بوده ؟
که پوش کنم به ریپو

**Comment by aliafshany** [comment]
اها گرفتم
دمت گرم

**Comment by EVOL-ution** [comment]
> سلام این اسکریپت که نوشتی رو تست کردی اوکی بوده ؟
> که پوش کنم به ریپو

بله میشه داتلود کرد مشکلی نداشت
