### ISSUE TITLE
Username or password is incorrect Error

### ISSUE THREAD

**Issue by Sufferer000** [sina-rostami/Adobe-Connect-Based-Meetings#18]
Event thought i write the correct username and password i cant download any recordings due to incorrect id,pw error. What should i do? When i try adding .zip to and of the recording link, it says i am not authorized to download it. i believe ADOBE fixed that flaw with downloading recordings as a zip file.

**Comment by sina-rostami** [comment]
which university?

**Comment by Sufferer000** [comment]
Suleyman Demirel Universty, School of Medicine; Turkey, Isparta

**Comment by sina-rostami** [comment]
your university isn't implemented in the code yet.
how do you try to add .zip to your meetings link??

**Comment by Sufferer000** [comment]
like below but it says i am not authorized to download
https://sdutip.adobeconnect.com/pzyjr5u6k20v/output/outputfile.zip?download=zip

sample link below
https://sdutip.adobeconnect.com/_a3787855616/pzyjr5u6k20v/?session=em2breezphzi9wv6sq2gy9b6

**Comment by sina-rostami** [comment]
can you open the recording of the meeting on-line and watch it?

**Comment by Sufferer000** [comment]
yes i can watch all of my school recordings of meetings online.
You can watch too links are not private no need for id pw

**Comment by sina-rostami** [comment]
yes I can, but after adding `/output/temp.zip?download=zip` to url, it needs login.
first login and go to watch meeting recording online,
then add `/output/temp.zip?download=zip`.
not authorized must be fixed.

**Comment by Sufferer000** [comment]
> yes I can, but after adding `/output/temp.zip?download=zip` to url, it needs login.
> first login and go to watch meeting recording online,
> then add `/output/temp.zip?download=zip`.
> not authorized must be fixed.

Can you please provide me adobe connect login webpage link because i couldn't find it and trying to log in after adding /output/temp.zip?download=zip to url doesn't work. 

Thanks.

**Comment by sina-rostami** [comment]
> > yes I can, but after adding `/output/temp.zip?download=zip` to url, it needs login.
> > first login and go to watch meeting recording online,
> > then add `/output/temp.zip?download=zip`.
> > not authorized must be fixed.
> 
> Can you please provide me adobe connect login webpage link because i couldn't find it and trying to log in after adding /output/temp.zip?download=zip to url doesn't work.
> 
> Thanks.

I think this is the link
[login page](https://sdutip.adobeconnect.com/system/login)

**Comment by Sufferer000** [comment]
> > > yes I can, but after adding `/output/temp.zip?download=zip` to url, it needs login.
> > > first login and go to watch meeting recording online,
> > > then add `/output/temp.zip?download=zip`.
> > > not authorized must be fixed.
> > 
> > 
> > Can you please provide me adobe connect login webpage link because i couldn't find it and trying to log in after adding /output/temp.zip?download=zip to url doesn't work.
> > Thanks.
> 
> I think this is the link
> [login page](https://sdutip.adobeconnect.com/system/login)

after i log in through this link, it still says i am not authorized. Just to be sure are you able to download recordins after adding /output/temp.zip?download=zip to url ? Or ADOBE banned that feature for every user maybe?

**Comment by sina-rostami** [comment]
yes I can, this is the base of this project.
maybe your uni admin banned this feature too! 🤯
