### ISSUE TITLE
خطا در کانورت

### ISSUE THREAD

**Issue by S3Y3D** [sina-rostami/Adobe-Connect-Based-Meetings#19]
سلام 
خیلی خوب دانلود کرد ولی موقع کانورت این خطا رو داد
ممنون
![Screenshot 2021-04-15 225640](https://user-images.githubusercontent.com/59525413/114919874-0bea5680-9e3e-11eb-9f9d-29aee3a68829.png)
ضمنا عرض کنم تمام پکیج های مورد نیاز رو هم نصب کردم

**Comment by SinaKarimi7** [comment]
I think it's would be resolved by using `virtualenv`.

```bash
> virtualenv venv
> source ./venv/bin/activate
> pip install -r requirements.txt
```

**Comment by S3Y3D** [comment]
WSL2 سلام نه روی 
بودم؛ سوئیچ کردم به مفسر روی ویندوز درست شد
