### ISSUE TITLE
دانلود پرزنتیشن (صدا + pdf)

### ISSUE THREAD

**Issue by FeryET** [sina-rostami/Adobe-Connect-Based-Meetings#22]
سلام

همونطور که می‌دونید اگه پرزنتیشن آپلود شده باشه به صورتی که screensharing نداشته باشیم
نمی‌شه با روش شما صدا و تصویر رو با هم دانلود کرد
و فقط صدا دانلود می‌شه

می‌خواستم بدونم روشی هست که بشه تصویر رو برای صدا هم جنریت کرد؟

من تو چندتا ریپوی دیگه دیدم که میان با سلنیوم اسکرین شات میگیرن و بعد میندازن رو صدا. نظری دارید؟

**Comment by sina-rostami** [comment]
سلام روش هایی هست برای اینکار ولی باگ زیاد داره
مثلا اگر هیچ پی دی افی هم شیر نشده باشه چی؟
الان پرزنتیشن اگ پی دی اف یا پاور پوینت باشه دانلود میشه کنار همون صدا.
ادرس ریپو ها رو اگر بزارید ببینم شاید ایده خوبی داشته باشن. مرسی

**Comment by FeryET** [comment]
سلام دوباره
من نتونستم از این ریپو استفاده کنم چون دانشگاه تهران یه خرده سیستمش متفاوته اینجور که فهمیدم اونجوری که کانکت رو آوردن بالا.

https://github.com/amirheidarikhoram/adobe-connect-session-recorder

چیزی که ایشون توضیح داده اینه که مرتب اسکرین شات می‌گیره مثکه با خوندن اون xml بعد اینا رو با هم سینک میکنه.

من الان از ابزار شما استفاده میکنم که صدا رو گوش بدم موقع خوندن پی دی اف ولی خب مشکلی که وجود داره بعضی وقتا از دست میدم و این‌ها. هر چند واقعاً ابزار شما خیلی به کارم اومده و دمتون گرم کلی.

**Comment by sina-rostami** [comment]
حله میخونم اگه ممکن بود پیاده سازیشو انجام میدم.
خواهش میکنم خوشحالم که به کارتون اومده ممنون میشم به دوستاتون معرفی کنید و به ریپو استار بدید 😃
