### ISSUE TITLE
چند پیشنهاد و سوال

### ISSUE THREAD

**Issue by miladshakerdn** [sina-rostami/Adobe-Connect-Based-Meetings#26]
<p dir="rtl">
سلام، یه چندتا پیشنهاد داشتم گفتم همینجا بگم در مورد ترکیب ویدئوها و صوت‌ها:
</p>
<p dir="rtl">
اساتید معمولا دو سه بار در طول یک جلسه اسکرین رو قطع و صل میکنند و فقط صوت پخش میشه و یا بلعکسش. ما بیاییم کاری کنیم خروجی یک ویدئو واحد بشه، مثلا از ثانیه 30 تا 60 ویدئویی برای پخش نیست ولی صوت هست و این صوت پخش بشه در این بازه بعد حالا اگر ویدئویی بود بعد از این صوت پخش بشه و همینطور این روند ادامه پیدا کنه تا پایان کلاس
</p>
<p dir="rtl">
برای این کار میتونیم مثلا یک فایل ویدئویی کامل به عنوان خروجی ایجاد کنیم که مستلزم کمی پردازش هست و یا بیاییم با کد نویسی بیشتر مثلا با استفاده از جاوااسکریپت و vujs و پی‌اچ‌پی یا پایتون یک وب‌سرور داخلی ایجاد کنیم که این فایل ها رو تمیز و مرتب پخش کنه. انگار که دوباره ادوب کانت رو ساختیم ( اختراع دوباره چرخ)
</p>
</p>
<p dir="rtl">
کامنت‌ها هم میتونه مثل زیر نویس فیلم باشه 
</p>
<p dir="rtl">
و یک سوال هم داشتم، چطور زمان شروع و پایان فیلم ها رو پیدا کنم؟ که صوت های توی اون بازه رو به فیلم اضافه کنم
</p>

<p dir="rtl">
دارم روی سورس کد شما کار میکنم، یکسری ترفند هم میزنم خیلی سریع فایل ها concat میشوند
</p>

**Comment by miladshakerdn** [comment]
<p dir="rtl">
سوالام در مورد زمان شروع پایان... حل شد. ایشالا اگر از زیر دست اساتید وقت خالی پیدا کنم، مشکل گرفتن خروجی ویدئو کامل ( پر سرعت) رو حل میکنم و میفرستم براتون
</p>

**Comment by sina-rostami** [comment]
سلام بسیار عالی
متشکرم.
اگر بازم سوالی بود درخدمتم
