### ISSUE TITLE
مشکل تصوير 

### ISSUE THREAD

**Issue by MhYavari** [sina-rostami/Adobe-Connect-Based-Meetings#28]
سلام اول ازت تشکر کنم بخاطر برنامه اي که ساختي خيلي عاليه و کاربردي 

دوم اينکه که دوتا مشکل براي دانشگاه ما داشت مشکل اوول اينه که بعضي از استادا اسکرين شير نميکنند و از روي پي دي اف آپلود شده درس ميدن و روي اون مينويسن که مشکل اينجا بود که براي اون جلسات کلا فقط يه فايل صوتي ايجاد ميکرد 
و مشکل دوم اينکه براي اونايي که اسکرينشون رو هم شير ميکنند فايل تصوير و صدا جدا از همه

**Comment by sina-rostami** [comment]
سلام خواهش می‌کنم.

کدوم دانشگاه هستین؟
خود پی دی اف رو هم باید دانلود کنه.

و اسکرین شیر هم اره بخاطر تایم زیادی که میگیره اضافه کردن صدا به تصویر فعلا اضافه نکردم. تو ورژن های بعدی به زودی اضافه میشه این قابلیت.

**Comment by MhYavari** [comment]
من صنعتي تبريزهستم 
بله پي دي اف رو دارم اما حرکات موس (منظورم همون نوشتار با قلم هست)رو خير 
من راستش بخش زيادي از گيتهاب رو چک کردم خيلي از پروژ هارو ديدم اما هنوز نتيجه نگرفتم شما خودتون نتيجه گرفتيد طوري که ريزالتش دقيقا مثل پخش خود برنامه بوده باشه؟

**Comment by sina-rostami** [comment]
نه این قابلیت رو به این سادگی ها نمیشه ایجاد کرد. تو فایل های دانلود شده کاملا جدا هستن از همدیگه.

از طرفی وقتی صوت رو پخش کنید و پی دی اف هم جلوتون باز باشه مشخص میشه کجاش هست و میشه با استاد رفت جلو تا حد زیادی....

**Comment by MhYavari** [comment]
آها بازم ممنون
