### ISSUE TITLE
پیشنهاد برای بهبود

### ISSUE THREAD

**Issue by aliafshany** [sina-rostami/Adobe-Connect-Based-Meetings#29]
سلام
ممنونم از ریپو خوبی که داری
من یک پیشنهادی داشتم

در حال حاضر این ریپو خیلی سریع فایل اسکرین شیر شده و فایل صوتی کل جلسه رو قشنگ تحویل میده
<img width="387" alt="Screen Shot 2021-12-10 at 16 16 01" src="https://user-images.githubusercontent.com/40741745/145576213-13e51888-f2e1-4a02-9db3-c4d6bb661a8f.png">

اما نمیشه فعلا مرجش کرد چون تایم اسکرین شیر و صوتی یکی نیست.
من پیشنهاد میکنم در زمانی که اسکرینی شیر نشده و صرفا یک صدارو داریم در اون فواصل بیای از یک فایل ویدیویی اماده استفاده کنی و به میزانی که نیاز هست این فاصله رو پر بکنه

امیدوارم منظورم رو خوب رسونده باشم.

در این صورت چون صرفا یک بار خود ویدیو برای پر کردن گپ ها مرج میشه و یکبار هم کل ویدیوی خروجی با صوتی مرج میشه عملن سرعت تبدیل خیلی بالا خواهد بود.

واقعا اگر بشه عالی خواهد شد

ممنونم

**Comment by sina-rostami** [comment]
سلام خیلی ممنون از نظرتون
حتما بررسی‌ش می‌کنم اگر ممکن بود اضافه می‌کنم.
