### ISSUE TITLE
Audio/Video Mismatch

### ISSUE THREAD

**Issue by ali-yz** [sina-rostami/Adobe-Connect-Based-Meetings#30]
Hi
Thanks for the nice script!

I used your tool for downloading a class from UT but the output video and audio files are not matched (video is almost 1 hour and the audio is about 2 hours). I was wondering what could be the issue?

**Comment by sina-rostami** [comment]
Hello,

The current scripts doesn't match and merger audio with video, audio will be generated from merging all played audios during the class and videos are downloaded directly from screen shares and uploaded videos in the class.

however I'm working on it to merge audio with video but I didn't find a general solution yet.
