### ISSUE TITLE
Make it usable for every Adobe Connect Meeting 

### ISSUE THREAD

**Issue by ChocolateFr** [sina-rostami/Adobe-Connect-Based-Meetings#33]
چرا اپشن اینکه خودمون لینک کاستوم بدیم ( تو GUI) رو نذاشتید؟

**Comment by sina-rostami** [comment]
سلام
چون دیدن اون لینک ها معمولا نیاز به لاگین کردن داره و با صرف کپی کردن لینک نمیشه جلسه رو دانلود کرد.

**Comment by hosseinniri** [comment]
یه سری لینک پابلیک هم هست که نیاز به لاگین نداره اصلا
برا اونا هم نمیشه کاری کرد؟

**Comment by sina-rostami** [comment]
> یه سری لینک پابلیک هم هست که نیاز به لاگین نداره اصلا برا اونا هم نمیشه کاری کرد؟

سلام، بله میشه. در توضیحات صفحه اول پروژه گزینه سوم Usage رو بررسی بفرمایید.
and if your institute isn't supported yet...
با این روش باید انجام بشه.

**Comment by hosseinniri** [comment]
> > یه سری لینک پابلیک هم هست که نیاز به لاگین نداره اصلا برا اونا هم نمیشه کاری کرد؟
> 
> سلام، بله میشه. در توضیحات صفحه اول پروژه گزینه سوم Usage رو بررسی بفرمایید. and if your institute isn't supported yet... با این روش باید انجام بشه.

خب در این روش داخل فایل info.txt باید user و pass بذاریم درسته؟
من یوزر و پسی ندارم اصلا 
خالی بذارم اوکیه؟

**Comment by sina-rostami** [comment]
بله در این روش فایل info.txt مهم نیست. فقط فایل های زیپ دانلود شده رو داخل یه پوشه به اسم temp کنار کد ها بریزید و کد export_only رو اجرا کنید.
